### ISSUE TITLE
database

### ISSUE THREAD

**Issue by itchris2** [kojouchearthur/assetmgtsys#1]
Hi can please tell me where the database are can't seem to find it

**Comment by kojouchearthur** [comment]
Hey @itchris2 please send me an email. I'll send a copy of the demo DB to you. Also, you should take a pull of the branch to_delete_device_user because it contains modifications that match the latest DB design :)

**Comment by itchris2** [comment]
Thank you so much my email is cashitcc01@gmail.com much appreciated

**Comment by itchris2** [comment]
Hey @kojouchearthur i didn't received a copy of the database yet

**Comment by kamauEr** [comment]
Can i get a copy? 
eriqoz99@gmail.com
